# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

  # Maintain dependencies for gitsubmodule
- package-ecosystem: gitsubmodule
  directory: /
  schedule:
    interval: daily

  # Maintain dependencies for pip
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily

# Enable version updates for Docker
- package-ecosystem: docker
  # Look for a `Dockerfile` in the `root` directory
  directory: /
  # Check for updates once a week
  schedule:
    interval: weekly
