name: ci


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  docker-build:
    uses: PurpleBooth/common-pipelines/.github/workflows/docker-build.yml@v0.4.2

  version:
    uses: PurpleBooth/common-pipelines/.github/workflows/commit-check.yml@v0.4.2

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - docker-build
      - version
    outputs:
      version_bump: ${{ steps.release.outputs.version_bump }}
      current_version: ${{ steps.release.outputs.current_version }}
      previous_version: ${{ steps.release.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: PurpleBooth/versio-release-action@v0.1.2
        id: release

  generate-github-release:
    if: needs.release.outputs.version_bump
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          lfs: true
          fetch-depth: 0
          ref: v${{ needs.release.outputs.current_version }}
      - uses: actions/download-artifact@v2
      - name: Generate a changelog
        uses: PurpleBooth/changelog-action@v0.1.1
        with:
          config: cliff.toml
          args: --verbose --latest
          output: CHANGELOG.md
      - id: create_release
        uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "CHANGELOG.md"
          name: Release v${{ needs.release.outputs.current_version }}
          tag: v${{ needs.release.outputs.current_version }}

  docker-push:
    if: needs.release.outputs.version_bump
    needs:
      - release
    uses: PurpleBooth/common-pipelines/.github/workflows/docker-push.yml@v0.4.2
    with:
      current_version: ${{ needs.release.outputs.current_version }}

